name: gitartwork from a contribution graph

on: 
  push:  # Ejecuta el workflow cada vez que empujes cambios

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Clona tu repositorio

    - uses: jasineri/gitartwork@v1  # Usa el GitHub Action de gitartwork
      with:
        user_name: ffloresm30  # Tu nombre de usuario en GitHub
        text: "Machine Learning Enthusiast"  # Texto que quieres mostrar en el gráfico

    - uses: jasineri/simple-push-action@v1  # Empuja el archivo generado a tu repositorio
